[package]
name = "apheleia_bookwyrm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
apheleia_prism = { version = "0.1.0", path = "../apheleia_prism" }
logos = "0.13.0"
